# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('arts', 'arts'),
        ('git_gui/presentation/theme/builtin', 'git_gui/presentation/theme/builtin'),
    ],
    hiddenimports=[
        '_cffi_backend',
        'git_gui.presentation.theme.builtin',
        # _build_config is generated by release.yml just before the build and
        # imported lazily inside a try/except in observability.py. PyInstaller's
        # static analyzer can miss conditional/function-scope imports — listing
        # it here forces inclusion so _get_version() finds the baked version at
        # runtime instead of silently falling back to "unknown".
        'git_gui._build_config',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
    cipher=block_cipher,
    collect_all=['pygit2'],
)

pyz = PYZ(a.pure, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='GitCrisp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='GitCrisp',
)

app = BUNDLE(
    coll,
    name='GitCrisp.app',
    icon=None,
    bundle_identifier='com.gitcrisp.app',
    info_plist={
        'CFBundleShortVersionString': '0.1.0',
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '12.0',
    },
)
