# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

sys.path.insert(0, str(Path(SPECPATH)))
from git_gui.observability import _get_version

block_cipher = None


def _bundle_version():
    """The version to stamp into the macOS bundle.

    Read through the same resolver the running app uses, so what Finder shows
    and what the app reports cannot disagree. This was a literal '0.1.0' for
    twenty-six releases: every .app since v0.1.0 claimed to be v0.1.0 in Get
    Info and in About, whatever tag had built it.

    A local build has no baked version and resolves to 'unknown', which is not
    a version string a plist accepts — 0.0.0 marks it as the dev build it is.
    """
    version = _get_version()
    return '0.0.0' if version == 'unknown' else version

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('arts', 'arts'),
        ('git_gui/presentation/theme/builtin', 'git_gui/presentation/theme/builtin'),
    ],
    hiddenimports=[
        '_cffi_backend',
        'git_gui.presentation.theme.builtin',
        # _build_config is generated by release.yml just before the build and
        # imported lazily inside a try/except in observability.py. PyInstaller's
        # static analyzer can miss conditional/function-scope imports — listing
        # it here forces inclusion so _get_version() finds the baked version at
        # runtime instead of silently falling back to "unknown".
        'git_gui._build_config',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
    cipher=block_cipher,
    collect_all=['pygit2'],
)

pyz = PYZ(a.pure, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='GitCrisp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='GitCrisp',
)

app = BUNDLE(
    coll,
    name='GitCrisp.app',
    icon=None,
    bundle_identifier='com.gitcrisp.app',
    info_plist={
        'CFBundleShortVersionString': _bundle_version(),
        'CFBundleVersion': _bundle_version(),
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '12.0',
    },
)
