"""Static checks on GitCrisp.spec to catch packaging regressions.

These are NOT a substitute for actually running PyInstaller — they just
catch obvious mistakes (missing hiddenimport, missing data dir) that
would otherwise only surface in a packaged binary on a user's machine.
"""

from __future__ import annotations

from pathlib import Path

SPEC_PATH = Path(__file__).resolve().parent.parent / "GitCrisp.spec"


def _read_spec() -> str:
    return SPEC_PATH.read_text(encoding="utf-8")


def test_build_config_is_in_hiddenimports():
    """`git_gui._build_config` must be listed in hiddenimports.

    It is generated by release.yml just before PyInstaller runs and
    imported lazily inside a try/except in observability.py. Without
    an explicit hidden-import entry, PyInstaller's static analyzer
    can miss it and the bundled app falls back to 'unknown' for its
    version — silently breaking the auto-updater.
    """
    assert "'git_gui._build_config'" in _read_spec(), (
        "git_gui._build_config must be in GitCrisp.spec hiddenimports; "
        "without it the release build has no baked version and the "
        "auto-updater silently skips the check."
    )


def test_theme_builtin_is_in_hiddenimports():
    """Sanity check that hiddenimports still includes the theme module
    — guards against accidental wholesale rewrite of the list."""
    assert "'git_gui.presentation.theme.builtin'" in _read_spec()


def test_exe_names_an_icon():
    """EXE must pass `icon=`, and not because a missing one means "no icon".

    PyInstaller substitutes its own icon when the argument is absent, so every
    Windows build before this was set shipped an exe wearing PyInstaller's
    feather. An empty `icon=` argument would silently restore that.
    """
    spec = _read_spec()
    assert "icon=_ICON," in spec, "EXE must pass icon=_ICON"
    assert "'win32': 'arts/gitcrisp.ico'" in spec
    assert (SPEC_PATH.parent / "arts" / "gitcrisp.ico").exists()


def test_bundle_names_an_icon():
    """BUNDLE carried `icon=None` for every release so far, which is why
    GitCrisp.app showed Finder's blank-document placeholder."""
    spec = _read_spec()
    assert "icon='arts/gitcrisp.icns'" in spec, "BUNDLE must point at the .icns"
    assert (SPEC_PATH.parent / "arts" / "gitcrisp.icns").exists()
