"""Static checks on GitCrisp.spec to catch packaging regressions.

These are NOT a substitute for actually running PyInstaller — they just
catch obvious mistakes (missing hiddenimport, missing data dir) that
would otherwise only surface in a packaged binary on a user's machine.
"""

from __future__ import annotations

from pathlib import Path

SPEC_PATH = Path(__file__).resolve().parent.parent / "GitCrisp.spec"


def _read_spec() -> str:
    return SPEC_PATH.read_text(encoding="utf-8")


def test_build_config_is_in_hiddenimports():
    """`git_gui._build_config` must be listed in hiddenimports.

    It is generated by release.yml just before PyInstaller runs and
    imported lazily inside a try/except in observability.py. Without
    an explicit hidden-import entry, PyInstaller's static analyzer
    can miss it and the bundled app falls back to 'unknown' for its
    version — silently breaking the auto-updater.
    """
    assert "'git_gui._build_config'" in _read_spec(), (
        "git_gui._build_config must be in GitCrisp.spec hiddenimports; "
        "without it the release build has no baked version and the "
        "auto-updater silently skips the check."
    )


def test_theme_builtin_is_in_hiddenimports():
    """Sanity check that hiddenimports still includes the theme module
    — guards against accidental wholesale rewrite of the list."""
    assert "'git_gui.presentation.theme.builtin'" in _read_spec()
