from __future__ import annotations
from typing import Protocol, runtime_checkable
from git_gui.domain.entities import Branch, Commit, FileStatus, Hunk, Stash, Tag


@runtime_checkable
class IRepositoryReader(Protocol):
    def get_commits(self, limit: int, skip: int = 0, extra_tips: list[str] | None = None) -> list[Commit]: ...
    def get_commit(self, oid: str) -> Commit: ...
    def get_branches(self) -> list[Branch]: ...
    def get_stashes(self) -> list[Stash]: ...
    def get_commit_files(self, oid: str) -> list[FileStatus]: ...
    def get_file_diff(self, oid: str, path: str) -> list[Hunk]: ...
    def get_staged_diff(self, path: str) -> list[Hunk]: ...
    def get_working_tree(self) -> list[FileStatus]: ...
    def is_dirty(self) -> bool: ...
    def get_head_oid(self) -> str | None: ...
    def get_tags(self) -> list[Tag]: ...
    def get_remote_tags(self, remote: str) -> list[str]: ...


@runtime_checkable
class IRepositoryWriter(Protocol):
    def stage(self, paths: list[str]) -> None: ...
    def unstage(self, paths: list[str]) -> None: ...
    def stage_hunk(self, path: str, hunk_header: str) -> None: ...
    def unstage_hunk(self, path: str, hunk_header: str) -> None: ...
    def commit(self, message: str) -> Commit: ...
    def checkout(self, branch: str) -> None: ...
    def checkout_commit(self, oid: str) -> None: ...
    def checkout_remote_branch(self, remote_branch: str) -> None: ...
    def create_branch(self, name: str, from_oid: str) -> Branch: ...
    def delete_branch(self, name: str) -> None: ...
    def merge(self, branch: str) -> None: ...
    def rebase(self, branch: str) -> None: ...
    def push(self, remote: str, branch: str) -> None: ...
    def pull(self, remote: str, branch: str) -> None: ...
    def fetch(self, remote: str) -> None: ...
    def fetch_all_prune(self) -> None: ...
    def stash(self, message: str) -> None: ...
    def pop_stash(self, index: int) -> None: ...
    def apply_stash(self, index: int) -> None: ...
    def drop_stash(self, index: int) -> None: ...
    def create_tag(self, name: str, oid: str, message: str | None = None) -> None: ...
    def delete_tag(self, name: str) -> None: ...
    def push_tag(self, remote: str, name: str) -> None: ...


@runtime_checkable
class IRepoStore(Protocol):
    def load(self) -> None: ...
    def save(self) -> None: ...
    def get_open_repos(self) -> list[str]: ...
    def get_recent_repos(self) -> list[str]: ...
    def get_active(self) -> str | None: ...
    def add_open(self, path: str) -> None: ...
    def close_repo(self, path: str) -> None: ...
    def remove_recent(self, path: str) -> None: ...
    def set_active(self, path: str) -> None: ...


@runtime_checkable
class IRemoteTagCache(Protocol):
    def load(self, repo_path: str) -> dict[str, list[str]]: ...
    def save(self, repo_path: str, data: dict[str, list[str]]) -> None: ...
